Update patch set 4
Patch Set 4:

authdns::lint requires GeoIP with volatile data but:

 Info: Could not find filesystem info for file 'volatile/GeoIP' in environment production
 Error: /Stage[main]/Geoip::Data::Puppet/File[/usr/share/GeoIP]: Could not evaluate: Could not retrieve information from environment production source(s) puppet:///volatile/GeoIP

:-(

Patch-set: 4