Update patch set 18
Patch Set 18:

PS18
* pass the repository variable when invoking the npm-oid and setup-npm-oid macro or the {repository} is not expanded
* fix a missing double quotes in the shell

I have created the jobs:

 + exec jenkins-jobs --conf jenkins_jobs.ini update config/jjb '*cxserver*'
 INFO:root:Updating jobs in ['config/jjb'] (['*cxserver*'])
 INFO:jenkins_jobs.builder:Creating jenkins job cxserver-deploy-npm
 INFO:jenkins_jobs.builder:Creating jenkins job cxserver-source-npm

Triggers them manually via the web interface and both fails with:

 Fatal error: Unable to find local grunt.

https://integration.wikimedia.org/ci/job/cxserver-deploy-npm/3/console
https://integration.wikimedia.org/ci/job/cxserver-source-npm/4/console

Patch-set: 18
Label: Verified=0