[mediawiki-config] use full path to composer.json
When injecting the composer require-dev with tools/composer-dev-args.js,
it fails with:
 Error: Cannot find module 'composer.json'

Causes the script to fall back to phpunit/phpunit=3.7.37 which is not
what we expect.

Use an absolute path to satisfy nodejs require().

Update:
  operations-mw-config-composer-hhvm-jessie

Bug: T159431
Change-Id: Id433e7d1aa0c4fe294a4ac23a91c8ed1a6227d2f