Update patch set 2
Patch Set 2: Verified-1 Code-Review-1

[contint1001.wikimedia.org] sudo: /usr/sbin/service zuul reload
[contint1001.wikimedia.org] out: sudo: a password is required
[contint1001.wikimedia.org] out:


Fatal error: sudo() received nonzero return code 1 while executing!

Patch-set: 2
Label: Verified=-1
Label: Code-Review=-1