docker: add Chrome deps to java8-wikidata-query-rdf
wikidata/query/rdf runs gui tests which are going to be switched to
grunt-contrib-qunit 3.0 which uses Puppeteer and thus Chrome. We need
the system dependencies to be installed to avoid eg:

 Fatal error: Failed to launch chrome!
 /src/gui/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome:
error while loading shared libraries: libXcursor.so.1:
 cannot open shared object file: No such file or directory

Bug: T209776
Change-Id: Ifcad461402ac55d44765d4f656e16346ad709551