jjb: update quibble jobs for gitv2/stretch-backports [2]
First done with 24bf326d3a but GitPython 2.1.1 shipped with Stretch did
not play well with git 2.20.1 causing:

TypeError: PackingType of packed-Refs not understood:
 '# pack-refs with: peeled fully-peeled sorted'

The images have been rebuild using GitPython from pip (e2e62a037).

Bug: T256844
Change-Id: I002ca496a919bc935774c78e0ba6b05cc3cb7b47