Update patch set 3
Patch Set 3:

> `R CMD check` runs scripts in tests/, which is how testthat.R gets triggered and then runs the unit tests (if testthat is installed)

Ah thank you!! Sounds like a nice convention to have and that nicely explains why 'check' bails out :D

> lint checking via Jim Hester's lintr package can be added as a unit test and I had success using it that way in a different repo (wikimedia/discovery/polloi) but not ortiz (yet! :D)

Ortiz will get to it eventually :]



> OH! I just found the thing to do this. `devtools::install_deps("src", dependencies=TRUE)` installs suggested packages also *and* it's better to use this one over R's built-in installer because this also installs GitHub/Gerrit-hosted dependencies :)

Yeah so I gave it a try earlier and that fails to install dependencies of testthat (how annoying is that really!).

 $ R --vanilla --quiet -e 'install.packages("devtools", repos="http://cran.us.r-project.org")'
 $ R --vanilla --quiet -e 'devtools::install_deps("src", repos="http://cran.us.r-project.org", dependencies = TRUE )'

 Installing testthat
 '/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
   CMD INSTALL '/tmp/RtmpWGmJcO/devtools223653fc4db/testthat'  \
   --library='/home/hashar/Rpackages' --install-tests 
 
 ERROR: dependencies ‘crayon’, ‘praise’, ‘magrittr’ are not available for package ‘testthat’
 * removing ‘/home/hashar/Rpackages/testthat’
 Installation failed: Command failed (1)
 $

And testthat-1.0.2 has them in Imports:

 Imports: digest, crayon, praise, magrittr, R6, methods
 Suggests: devtools, withr, covr

Tt does not complain about digest and R6 since they are already installed being dependencies of devtools. 'methods' does not show up though which is yet another mystery.



I guess I can try to craft a very basic repository to reproduce and then we should raise it to upstream? :-(

Patch-set: 3
Label: Verified=0