python-jobs: Use remoteonly-zuul instead of remote-zuul
There is no local replication in labs. It creates pointless errors:
> ERROR: Reference path does not exist: /srv/ssd/gerrit/operations/puppet.git

It's not causing failures since remote-zuul falls back to a
regular clone from zuul.eqiad.wmnet – which is what remoteonly-zuul
does.

Change-Id: Icdf41729f8ab7abf60b3b20bda4adc6d8d08f237