Update patch set 2
Patch Set 2:

While this would be a good exception, tox (https://integration.wikimedia.org/ci/job/integration-config-tox-py27/975/consoleFull) currently wants all mwext- repos to have a php-composer-validate job.

 FAIL: test_mw_repos_have_composer_validate_job
 -----
 AssertionError: Project mediawiki/extensions/Citoid pipeline test must have either php-composer-validate or a *-composer job

This was previously provided by the template, but is now missing.

The job only triggers if composer.json is modified so it won't run, but it's there as insurance so that people can start using composer without it breaking and then having to be fixed through a non-voting phase.

Patch-set: 2
Reviewer: Krinkle <34@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Verified=0