jjb: fix race in beta-publish-deb
The job fails with:

ERROR: Failed to copy artifacts from scap-beta-deb with filter: *.deb

I am pretty sure it is a race condition:

* scap-beta-deb passes and is a success
* scap-beta-deb triggers beta-publish-deb job without waiting
* beta-publish-deb looks for the last successful scap-beta-deb build and
  tries to retrieve the artifacts. It fails
* scap-beta-deb archives the artifacts

Move the job triggering from builders to publishers and AFTER the
archival of artifact.
Make it blocking so that the parent job scap-beta-deb fails on error.

Bug: T249225
Change-Id: Ie64931c2ac4ec2e4358e3f1ebc574b39528d19ce