Update patch set 2
Patch Set 2:

But one of my patches failed because of this change.

There error that happens

ERROR: Reference path does not exist: /srv/ssd/gerrit/mediawiki/core.git

Patch-set: 2