Update patch set 1
Patch Set 1: Code-Review-1

gyp fails due to lack of python while building mmmagic

 Error: Can't find Python executable "python", you can set the PYTHON env variable.

Patch-set: 1
Label: Code-Review=-1