Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> For Wikibase https://integration.wikimedia.org/ci/job/selenium-daily-beta-Wikibase/16/console
> 
>  1) WikibaseRepoNonExistingItemPage the title should match:
>    'Q1xy' === 'Item:Q1xy'

Agreed. Problem is in the test (assertion failing), not in CI.

> For WikibaseLexeme https://integration.wikimedia.org/ci/job/selenium-daily-beta-WikibaseLexeme/15/console
> 
>  ERROR: Cannot find module '../../../Wikibase/repo/tests/selenium/wikibase.api'
> 
> 
> The job template clones the repository using the macro docker-ci-src-setup-simple, that uses the container releng/ci-src-setup-simple which only clones a single repository:
> 
>  cd /src
>  git init
>  git fetch --quiet --depth 1 "${ZUUL_URL}/${ZUUL_PROJECT}" "$ZUUL_REF"
>  git checkout FETCH_HEAD
> 
> 
> There is a jjb macro docker-ci-src-setup-mwext which uses the container releng/ci-src-setup and use the setup-mwext.sh script there. But that uses zuul cloner and clones mediawiki/core.
> 
> Maybe we can add a script in dockerfiles/ci-src-setup/ that would support cloning a list of repositories.

No. Please. It's such a code smell if a repository hardcodes path to files in another repository and just expects the file to be at a certain location.

> Or we use the same trick we did for mediawiki/core: create a npm package such as wdio-mediawiki.

That would be the way to solve the problem. The repository either has to put shared code in wdio-mediawiki or create package like wdio-mediawiki-wikibase.

Patch-set: 3
Reviewer: Zfilipin <487@e9e9afe9-4712-486d-8885-f54b72dd1951>
Work-in-progress: false