Revert "Convert npm, npm-test to docker-pkg"
npm 1.4.21 from Jessie fails when used behind a proxy:

 TypeError: Request path contains unescaped characters

That prevent us from bootstrapping npm with:

 "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "npm@3.8.3"


This reverts commit 2221c4280e86cb460e579aedd6617d8d23e1035f.

Bug: T177276
Change-Id: Ia18f22f8a081bb9d13eb67d14067161259014744