Revert "Move wikimedia-fundraising-civicrm to Nodepool"
drush install fails with:

WD php: CiviCRM_API3_Exception: Unknown extension: [error]
org.wikimedia.omnimail in civicrm_api3()
(line 45 of src/wikimedia/fundraising/crm/civicrm/api/api.php).
CiviCRM_API3_Exception: Unknown extension: org.wikimedia.omnimail in civicrm_api3()

This reverts commit 42a270506adc8ef7b209bd9303a41e7f07999f67.

Bug: T119140
Change-Id: I07c9aee3bf82369ac51f1124f2da2cce5e2b599c