Update patch set 9
Patch Set 9: Code-Review-1

The build is now passing, and the fresnel command as well as the shell script for mw-patch is correctly being installed.

But, when trying to use it, it fails because the quibble image ships with Node 6 instead of Node 10 still. Oops, forgot about that!



 krinkle@home$ docker run --rm -i --tty --volume /tmp --entrypoint /bin/sh docker-registry.wikimedia.org/releng/quibble-stretch-php70:0.0.28-1 -c 'bash'
 nobody@098fbed879c8:/workspace$ fresnel --help

  async function cli( command, ...params ) {
      ^^^^^^^^
  SyntaxError: Unexpected token function
    at Object.<anonymous> (/opt/fresnel/node_modules/fresnel/bin/fresnel.js:9:1)
 nobody@098fbed879c8:/workspace$ node --version
  v6.11.0

Patch-set: 9
Reviewer: Krinkle <34@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Code-Review=-1