Update patch set 1
Patch Set 1:

https://integration.wikimedia.org/ci/job/integration-config-tox-docker/1/console

Since that runs with user nobody with home /nonexistent, it eventually fails:

 OSError: [Errno 13] Permission denied: '/nonexistent'

That is an integration test using JJB, and JJB tries to find a cache dir in $HOME. The jjb macro has some HOME=/var/lib/jenkins,  but I dont think that is passed to tox :D


I am tempted to have the Dockerfile to use something like:

 RUN install --directory /home
 USER nobody
 ENV HOME=/home
 WORKDIR /src

Patch-set: 1
Label: Verified=0