[LifeWeb] migrate to composer based job
It depends on Wikibase and that would not work with just vendor:

Fatal error: Class undefined: Wikibase\DataModel\Entity\ItemId
in extensions/Wikibase/lib/WikibaseLib.entitytypes.php on line 37

Switch to composer to provide depenendencies.

Bug: T104085
Change-Id: Id7c0adbb323f89b07272b0bf4e99a09d2267edfe