Run adb-setup before Android emulator tests
The Android instrumentation tests are failing in a strange way after
upgrading the Android Support libraries[0]:

com.android.builder.testing.api.TestException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.ShellCommandUnresponsiveException

This patch calls adb-setup before executing Android instrumentation
tests, which blocks until the device is ready to test before returning.
All non-Android instrumentation test dependencies are satisfied first to
minimize idle time.

Depends on adb-setup[1].

[0] https://gerrit.wikimedia.org/r/#/c/235859/
[1] https://gerrit.wikimedia.org/r/#/c/239898/

Change-Id: Ie950d0b3ca49fd9506f2d057c890fea6dbebe711