Revert "Don't shell out for test_have_no_tabs"
Eventually randomly causes:

 FAIL: test_have_no_tabs
 (test_files_structure.TestFilesStructure)
 AssertionError: /src/.git/config has tabs

os.walk() eventually parse the whole tree.
subprocess.check_call(git) only process tracked files.

This reverts commit 0794a78c04134863bec33ba0e1243a1fece7d197.

Bug: T208063
Change-Id: I308262f562ffa098f71639b1eca7885eb7e08b6a