Fix castor deleting /home/jenkins/workspace on Nodepool
4b7f18005 made castor-load to delete files at the destination. For
Docker jobs it is /cache which we actually want to be 100% in sync.

On Nodepool the destination is /home/jenkins and that ended up wiping
the job workspace.

It only surfaced for jobs using castor-load and deployed after 4b7f18005
since I have not updated all the jobs when merging that change.

Spotted on cumin-tox-publish which kept failling with:

[castor-load]
rsync --archive --delete-delay --compress --contimeout 3
rsync://castor02.integration.eqiad.wmflabs:/caches/operations-software-cumin/master/cumin-tox-publish/
/home/jenkins

And then:
    java.io.IOException: Process working directory
    '/home/jenkins/workspace/cumin-tox-publish' doesn't exist!

Jobs affected:

    cumin-tox-publish
    fundraising-tools-tox-jessie
    mw-tools-releng-tox-publish
    pywikibot-core-tox-publish
    pywikibot-tests-beta-cluster
    selenium-Popups-jessie

Bug: T179593
Change-Id: Ibdbc616dd7b24a5cd69540f445ff3681fe9452ec