Update patch set 3
Patch Set 3: Code-Review+2

Which yields:

 Dependency of gated project is in gate: AbuseFilter ... ok
 Dependency of gated project is in gate: AntiSpoof ... FAIL
 Dependency of gated project is in gate: BetaFeatures ... FAIL
 Dependency of gated project is in gate: Capiunto ... FAIL
 Dependency of gated project is in gate: CentralAuth ... FAIL
 Dependency of gated project is in gate: CheckUser ... ok
 Dependency of gated project is in gate: CirrusSearch ... ok
 Dependency of gated project is in gate: Cite ... FAIL
 Dependency of gated project is in gate: CodeEditor ... FAIL
 Dependency of gated project is in gate: Echo ... ok
 Dependency of gated project is in gate: EducationProgram ... FAIL
 Dependency of gated project is in gate: Elastica ... ok
 Dependency of gated project is in gate: EventLogging ... ok
 Dependency of gated project is in gate: Flow ... ok
 Dependency of gated project is in gate: GeoData ... ok
 Dependency of gated project is in gate: JsonConfig ... ok
 Dependency of gated project is in gate: MobileApp ... ok
 Dependency of gated project is in gate: MobileFrontend ... ok
 Dependency of gated project is in gate: PdfHandler ... FAIL
 Dependency of gated project is in gate: PropertySuggester ... FAIL
 Dependency of gated project is in gate: Scribunto ... FAIL
 Dependency of gated project is in gate: SiteMatrix ... ok
 Dependency of gated project is in gate: SyntaxHighlight_GeSHi ... FAIL
 Dependency of gated project is in gate: TimedMediaHandler ... ok
 Dependency of gated project is in gate: UniversalLanguageSelector ... ok
 Dependency of gated project is in gate: VisualEditor ... ok
 Dependency of gated project is in gate: WikiEditor ... FAIL
 Dependency of gated project is in gate: Wikibase ... ok
 Dependency of gated project is in gate: WikibaseLexeme ... FAIL
 Dependency of gated project is in gate: WikibaseMediaInfo ... FAIL
 Dependency of gated project is in gate: WikibaseQuality ... FAIL
 Dependency of gated project is in gate: WikibaseQualityConstraints ... FAIL
 Dependency of gated project is in gate: WikimediaBadges ... FAIL
 Dependency of gated project is in gate: ZeroBanner ... ok
 Dependency of gated project is in gate: ZeroPortal ... ok
 Dependency of gated project is in gate: cldr ... ok
 Dependency of gated project is in gate: skins/MinervaNeue ... FAIL

Then there are assertion messages such as:

 AssertionError: WikibaseQualityConstraints is not in gate but is a dependency of: Wikibase
 AssertionError: skins/MinervaNeue is not in gate but is a dependency of: MobileApp, MobileFrontend, Thanks, ZeroBanner, ZeroPortal

etc

Merging so we get a report generated.

Patch-set: 3
Reviewer: Hashar <24@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Code-Review=+2