layout: trigger-mediawiki-pipeline-dev to -publish
The pipeline in mediawiki/core/.pipeline/config.yaml is named
`publish` rather than `dev`:

    pipelines:
      publish:
        blubberfile: blubber.yaml
        stages:
          - name: dev
            build: dev
            publish:
              image: true
              tags: [dev]

...which I believe is causing this:

    java.lang.RuntimeException: Pipeline 'dev' is not defined in project's '.pipeline/config.yaml'

Example:

  https://integration.wikimedia.org/ci/job/mediawiki-pipeline-dev/538/console

Bug: T218360
Change-Id: I8184eaf37f57abaef1578481d996892ccc4afdd2