Replace python-minimal with python (full) in node10 dockerfiles
The python-minimal was added for node-gyp, but doesn't actually
work with just the minimal package, it needs other deps as well.
The first thing node-gyp builds on Node 10 fail on is:

> ImportError: No module named compiler.ast

Bug: T213944
Change-Id: I12a0f8e44616c3cbde3638ade4cfdd0ea94ffbb7