WIP: Fix: run NPM containers as "node" user
THIS PATCH IS UNTESTED and I'm new to Docker :]

Prior to this patch, NPM containers were executed as user "nobody" which
is preferable to root. However, this appears to be inadequate for
node-gyp dependent installations which report the following error:

  + npm install --no-progress
  > dtrace-provider@0.8.6 install /src/node_modules/dtrace-provider
  > node-gyp rebuild || node suppress-error.js

  gyp WARN EACCES user "jenkins-deploy" does not have permission to access the dev dir "/nonexistent/.node-gyp/6.11.0"
  gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
  Traceback (most recent call last):
   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
     import gyp
   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
     import gyp.input
   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
     from compiler.ast import Const
  ImportError: No module named compiler.ast
  gyp ERR! configure error
  gyp ERR! stack Error: `gyp` failed with exit code: 1
  gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
  gyp ERR! stack     at emitTwo (events.js:106:13)
  gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
  gyp ERR! System Linux 4.9.0-0.bpo.5-amd64
  gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
  gyp ERR! cwd /src/node_modules/dtrace-provider
  gyp ERR! node -v v6.11.0
  gyp ERR! node-gyp -v v3.3.1
  gyp ERR! not ok

This patch applies the [recommended fix] for a [very similar issue],
which is to run the container as the "node" user. The [docs] also
clarify that "node" is the preferred user:

  By default, Docker runs container as root which inside of the
  container can pose as a security issue. You would want to run the
  container as an unprivileged user wherever possible. The node images
  provide the node user for such purpose.

[very similar issue]: https://github.com/nodejs/docker-node/issues/424
[recommended fix]: https://github.com/nodejs/docker-node/issues/423#issuecomment-306470507
[docs]: https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user

Bug: T179552
Change-Id: Ia296d2d4b9cdc6899c39acc24e94fd22a35b7463