Clarify test error
TestZuulScheduler.getJob() might be passed a job that does not exist for
a (repo, pipeline). That raises a 'List out of range' error which is a
bit meaningless.

Catch the exception and raise a new one with a better message. Example:

Exception: No such job mediawiki-extensions-hhvm-jessie for
mediawiki/extensions/Translate in pipeline gate-and-submit

Change-Id: I95c2fc72ab90199e5e0bbdf570eab588f3438aa7