Update patch set 1
Patch Set 1:

I tried to drop 'composer update', but the job fails due to:

 Fatal error: Uncaught Error: Class 'SmashPig\Core\GlobalConfiguration' not found in /workspace/src/extensions/DonationInterface/DonationInterface.class.php:47

Eg:

https://integration.wikimedia.org/ci/job/quibble-donationinterface-REL1_31-php70-docker/56/console
https://integration.wikimedia.org/ci/job/quibble-donationinterface-REL1_31-php70-docker/55/console

:(

Patch-set: 1
Reviewer: Hashar <24@e9e9afe9-4712-486d-8885-f54b72dd1951>