Revert "Convert npm, npm-test to docker-pkg"
npm 1.4.21 from Jessie fails when used behind a proxy:
 TypeError: Request path contains unescaped characters
     at new ClientRequest (_http_client.js:52:11)
     at TunnelingAgent.exports.request (http.js:31:10)
     at TunnelingAgent.createSocket (/usr/lib/nodejs/tunnel-agent/index.js:117:25)

That prevent us from bootstrapping npm with:
 "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "npm@3.8.3"

I have jumped into that rabbit hole previously, basically the npm
version in Jessie does not support HTTP proxy.

Reference:
https://bugs.debian.org/801897 (has patches)
Got fixed in April 2014 via:
https://github.com/request/tunnel-agent/pull/8

This reverts commit 2221c4280e86cb460e579aedd6617d8d23e1035f.

Bug: T177276
Change-Id: Ia18f22f8a081bb9d13eb67d14067161259014744